### ISSUE TITLE
Formatação do comando "?coin"

### ISSUE THREAD

**Issue by joaopedroalb** [EdsonHTJ/pythonDiscordBot#2]
Não está sendo formatado a string na mensagem do comando **?coin** 
![image](https://user-images.githubusercontent.com/62646489/135181412-ba94fab7-b520-4dca-8e5a-6e86d4d26cba.png)

**Comment by EdsonHTJ** [comment]
fixed in https://github.com/EdsonHTJ/pythonDiscordBot/pull/6
